"""Trace every phrase of LLM prose back to the deterministic value it came from.

WHY THIS EXISTS
---------------
RingWatch's central claim is that the language model never produces a number — it only
writes sentences about numbers `core/` already computed. That claim is enforced by the
number-provenance guard in `ai/schema.py` and by an import-boundary test, but neither is
visible to someone reading the dashboard.

This module makes it visible. It splits a narrative into segments and marks which
deterministic evidence field each marked segment came from, so the interface can highlight
the corresponding part of the entity graph when a reader hovers the phrase. The proof stops
being "there is a test for that" and becomes something you can see.

WHY SEGMENTS AND NOT HTML
-------------------------
`annotate` returns a list of plain-text segments with optional refs, never a marked-up
string. The narrative is text generated by a language model; building HTML here and
trusting the template not to escape it would put model output directly into the DOM. The
template escapes each segment itself, so a model that emitted `<script>` would render it as
visible text rather than execute it.

WHAT IT WILL NOT DO
-------------------
It only ever *finds* values already present in both the prose and the evidence. It cannot
introduce a value, and if the model wrote a figure that is not in the evidence, this module
leaves it unmarked rather than inventing a source for it — though in practice such a
narrative would already have been rejected upstream by the schema validator.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# Evidence fields worth tracing, mapped to what they point at in the graph. "entities"
# highlights every entity node, "attributes" every attribute node, "all" the whole cluster.
NUMERIC_FIELDS: dict[str, str] = {
    "entity_count": "entities",
    "component_size": "entities",
    "transaction_count": "all",
    "flagged_transaction_count": "all",
    "core_number": "all",
    "max_degree": "all",
    "span_days": "all",
    "distinct_cards": "attributes",
    "distinct_addresses": "attributes",
    "distinct_email_domains": "attributes",
    "total_amount_inr": "all",
    "max_risk_score": "all",
    "mean_risk_score": "all",
}

# Small integers appear constantly in ordinary prose ("one of the two accounts"), so
# matching them would mark half the paragraph and mean nothing. The interesting values --
# amounts, risk scores, transaction counts -- are almost always above this.
MIN_TRACEABLE_INTEGER = 3

# Fields whose values are quantities rather than counts. Rendered with decimals because
# that is how a model writes them, and matched on the field rather than on the value.
DECIMAL_FIELDS = {"total_amount_inr", "max_risk_score", "mean_risk_score"}


@dataclass(frozen=True)
class Segment:
    """One run of narrative text, optionally traced to an evidence field."""

    text: str
    field: str | None = None
    target: str | None = None

    @property
    def traced(self) -> bool:
        return self.field is not None


def _candidates(evidence: dict) -> list[tuple[str, str, str]]:
    """(literal, field, target) triples to look for, longest literal first.

    Longest-first matters: with 12 transactions and a core number of 2, scanning for "2"
    before "12" would mark the "1" of twelve as a core number and leave a stray digit.
    """
    found: list[tuple[str, str, str]] = []

    for field, target in NUMERIC_FIELDS.items():
        value = evidence.get(field)
        if value is None:
            continue

        if field in DECIMAL_FIELDS:
            # Amounts and risk scores. Keyed on the FIELD, not on whether the value
            # happens to be integral: a total of 48114.00 is still an amount, and looking
            # for the bare "48114" would fail against the "48114.00" a model writes,
            # because the trailing-dot boundary rejects it.
            number = float(value)
            found.append((f"{number:.4f}", field, target))
            found.append((f"{number:.2f}", field, target))
            found.append((f"{number:,.2f}", field, target))
            if number.is_integer():
                found.append((f"{int(number)}", field, target))
                found.append((f"{int(number):,}", field, target))
        else:
            number = int(value)
            if number < MIN_TRACEABLE_INTEGER:
                continue
            found.append((str(number), field, target))
            if number >= 1000:
                found.append((f"{number:,}", field, target))

    # Attribute names link to one specific node in the graph, which is the most precise
    # highlight available and the most convincing to look at.
    for attribute in evidence.get("shared_attributes", []) or []:
        if attribute and attribute != "indirect_attribute_chain":
            found.append((str(attribute), f"attribute:{attribute}", f"attr:{attribute}"))

    # Deduplicate, keeping the longest literals first.
    seen: set[str] = set()
    unique: list[tuple[str, str, str]] = []
    for literal, field, target in sorted(found, key=lambda item: -len(item[0])):
        if literal and literal not in seen:
            seen.add(literal)
            unique.append((literal, field, target))
    return unique


def annotate(text: str, evidence: dict) -> list[Segment]:
    """Split `text` into segments, marking those that quote a deterministic value.

    Matching is bounded so that a value only counts when it stands alone: `1234` inside
    `51234` is not a match. Every returned segment's text concatenates back to exactly the
    input, which `tests/test_provenance.py` asserts -- the annotation is a view over the
    prose, never an edit of it.
    """
    if not text:
        return []

    candidates = _candidates(evidence)
    if not candidates:
        return [Segment(text)]

    pattern = re.compile(
        "|".join(f"(?<![\\w.]){re.escape(literal)}(?![\\w.])" for literal, _, _ in candidates)
    )
    lookup = {literal: (field, target) for literal, field, target in candidates}

    segments: list[Segment] = []
    cursor = 0
    for match in pattern.finditer(text):
        if match.start() > cursor:
            segments.append(Segment(text[cursor : match.start()]))
        literal = match.group()
        field, target = lookup.get(literal, (None, None))
        segments.append(Segment(literal, field=field, target=target))
        cursor = match.end()

    if cursor < len(text):
        segments.append(Segment(text[cursor:]))
    return segments


def annotate_to_dicts(text: str, evidence: dict) -> list[dict]:
    """JSON-serialisable form, for the exported artifact the dashboard renders."""
    return [
        {"text": segment.text, "field": segment.field, "target": segment.target}
        for segment in annotate(text, evidence)
    ]
